[tool.black]
line-length = 100
skip-magic-trailing-comma = "True"
target-version = ['py38']
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | migrations
)/
'''
